name = "kv-d1-benchmark"
main = "src/index.ts"
compatibility_date = "2023-12-18"

[[kv_namespaces]]
binding = "KV"
id = "5d46e32d11504bf68c2dd9dbf0e2e54e"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "kv-d1-benchmark"
database_id = "9ff05cef-9f76-42a3-b3b3-126b8dc3a00c"
